# Generated by Django 3.1.3 on 2020-12-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='height',
            field=models.CharField(default='123cm', max_length=5),
        ),
    ]
