# Generated by Django 3.1.3 on 2020-12-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_hero_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='height',
            field=models.CharField(default='12cm', max_length=5),
        ),
    ]
