# Generated by Django 3.1.3 on 2020-12-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20201210_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoreSpyTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porosity', models.FloatField(blank=True, default=None, null=True)),
                ('blobiness', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
