# Generated by Django 3.1.3 on 2020-12-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_porespytutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porespytutorial',
            name='blobiness',
            field=models.FloatField(blank=True, default=0.6, null=True),
        ),
        migrations.AlterField(
            model_name='porespytutorial',
            name='porosity',
            field=models.FloatField(blank=True, default=2, null=True),
        ),
    ]
