# Generated by Django 3.1.3 on 2020-12-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20201219_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='porespytutorial',
            name='dimension_x',
            field=models.FloatField(blank=True, default=500, null=True),
        ),
        migrations.AddField(
            model_name='porespytutorial',
            name='dimension_y',
            field=models.FloatField(blank=True, default=500, null=True),
        ),
        migrations.AlterField(
            model_name='porespytutorial',
            name='blobiness',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='porespytutorial',
            name='porosity',
            field=models.FloatField(blank=True, default=0.6, null=True),
        ),
    ]
