# Generated by Django 3.1.3 on 2020-12-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20201220_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoreSpyGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porosity', models.FloatField(blank=True, default=0.6, null=True)),
                ('blobiness', models.IntegerField(blank=True, default=2, null=True)),
                ('dimension_x', models.IntegerField(blank=True, default=500, null=True)),
                ('dimension_y', models.IntegerField(blank=True, default=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PoreSpyTutorial',
        ),
    ]
