# Generated by Django 3.1.3 on 2020-12-24 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20201223_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoreSpyGenerator',
            new_name='PoreSpyTutorial',
        ),
    ]
