# Generated by Django 3.1.3 on 2020-12-24 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_auto_20201223_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoreSpyTutorial',
            new_name='PoreSpyGenerator',
        ),
    ]
