# Generated by Django 3.1.3 on 2021-01-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_auto_20201223_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
