# Generated by Django 3.1.3 on 2021-01-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_delete_hero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoreSpyGenerator',
            new_name='GeneratorBlobs',
        ),
    ]
