# Generated by Django 3.1.3 on 2021-01-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_generatorblobs_dimension_z'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoreSpyFuncs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='generatorblobs',
            name='dimension_z',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
