# Generated by Django 3.1.3 on 2021-01-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_auto_20210125_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='porespyfuncs',
            name='porosity',
            field=models.FloatField(blank=True, default=0.6, null=True),
        ),
    ]
