# Generated by Django 3.1.3 on 2021-01-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_porespyfuncs_porosity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoreSpyFuncsNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcnames', models.FloatField(blank=True, default=0.6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PoreSpyFuncs',
        ),
    ]
