# Generated by Django 3.1.3 on 2021-01-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_auto_20210125_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porespyfuncsnames',
            name='funcnames',
        ),
    ]
