# Generated by Django 3.1.3 on 2021-02-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_remove_porespyfuncsnames_funcnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorBundleOfTubes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_x', models.IntegerField(blank=True, default=500, null=True)),
                ('dimension_y', models.IntegerField(blank=True, default=500, null=True)),
                ('dimension_z', models.IntegerField(blank=True, default=0, null=True)),
                ('spacing', models.FloatField(blank=True, default=30, null=True)),
            ],
        ),
    ]
