# Generated by Django 3.1.3 on 2021-02-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_generatorbundleoftubes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestClassWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
