# Generated by Django 3.1.3 on 2021-02-19 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_auto_20210218_2259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneratorBundleOfTubes',
            new_name='BundleOfTubes',
        ),
    ]
