# Generated by Django 3.1.3 on 2021-03-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_auto_20210218_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalThickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
