# Generated by Django 3.1.3 on 2021-03-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0023_auto_20210314_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoreSizeDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psd_im', models.TextField(default='')),
            ],
        ),
    ]
