# Generated by Django 3.1.3 on 2021-03-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0024_poresizedistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='localthickness',
            name='mode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='localthickness',
            name='sizes',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
