# Generated by Django 3.1.3 on 2021-03-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0025_auto_20210316_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='poresizedistribution',
            name='bins',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='poresizedistribution',
            name='log',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poresizedistribution',
            name='voxel_size',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
