# Generated by Django 3.1.3 on 2021-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0026_auto_20210318_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='poresizedistribution',
            name='x_axis_label',
            field=models.TextField(default='invasion size [voxels]'),
        ),
        migrations.AddField(
            model_name='poresizedistribution',
            name='y_axis_label',
            field=models.TextField(default='volume fraction invaded [voxels]'),
        ),
    ]
