# Generated by Django 3.1.3 on 2021-04-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0027_auto_20210319_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatticeSpheres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_x', models.IntegerField(blank=True, default=500, null=True)),
                ('dimension_y', models.IntegerField(blank=True, default=500, null=True)),
                ('dimension_z', models.IntegerField(blank=True, default=0, null=True)),
                ('radius', models.IntegerField(blank=True, default=0, null=True)),
                ('offset', models.IntegerField(blank=True, default=0, null=True)),
                ('lattice', models.TextField(default='sc')),
            ],
        ),
    ]
